create table public.contatos (
    id bigint generated by default as identity primary key,
    nome_contato text not null,
    phone text not null,
    enviado boolean default false,
    enviado_em timestamptz
);